trigger:
- main
steps:
- script: curl -L 'https://spectral-eu.dome9.com/latest/x/sh?dsn=$(SPECTRAL_DSN)' | sh
  displayName: 'Install Spectral'
- script: $HOME/.spectral/spectral scan --ok --dsn $(SPECTRAL_DSN)
  displayName: 'Spectral Scan'
